"""sprint1_catalog

Revision ID: 86796390003b
Revises:
Create Date: 2026-10-02 06:29:38.250425
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '86796390003b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['genres.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_genres_slug')
    )
    op.create_table('ingestion_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_name', sa.String(length=120), nullable=False),
    sa.Column('rights_basis', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_confidence', sa.Float(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('artists_imported', sa.Integer(), nullable=False),
    sa.Column('releases_imported', sa.Integer(), nullable=False),
    sa.Column('tracks_imported', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('markets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('market_key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('iso_code', sa.String(length=2), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['markets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_code'),
    sa.UniqueConstraint('market_key', name='uq_markets_market_key')
    )
    op.create_table('artists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('source_batch_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_batch_id'], ['ingestion_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artists_name', 'artists', ['name'], unique=False)
    op.create_table('releases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('source_batch_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_batch_id'], ['ingestion_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_releases_title', 'releases', ['title'], unique=False)
    op.create_table('artist_genres',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('genre_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id', 'genre_id', name='uq_artist_genres_pair')
    )
    op.create_table('tracks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('isrc', sa.String(length=12), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('release_id', sa.String(length=36), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('source_batch_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_batch_id'], ['ingestion_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isrc', name='uq_tracks_isrc')
    )
    op.create_index('ix_tracks_title', 'tracks', ['title'], unique=False)
    op.create_table('external_identifiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('identifier', sa.String(length=160), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=True),
    sa.Column('release_id', sa.String(length=36), nullable=True),
    sa.Column('track_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint("entity_type IN ('artist', 'release', 'track')", name='ck_external_identifier_entity_type'),
    sa.CheckConstraint('(artist_id IS NOT NULL AND release_id IS NULL AND track_id IS NULL) OR (artist_id IS NULL AND release_id IS NOT NULL AND track_id IS NULL) OR (artist_id IS NULL AND release_id IS NULL AND track_id IS NOT NULL)', name='ck_external_identifier_one_owner'),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'entity_type', 'identifier', name='uq_external_identifiers_identity')
    )
    op.create_table('track_artists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('track_id', sa.String(length=36), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'artist_id', name='uq_track_artists_pair')
    )
    op.create_table('track_genres',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('track_id', sa.String(length=36), nullable=False),
    sa.Column('genre_id', sa.String(length=36), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('data_confidence', sa.Float(), nullable=False),
    sa.Column('source_batch_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('data_confidence >= 0 AND data_confidence <= 1', name='ck_track_genres_confidence'),
    sa.CheckConstraint('weight > 0 AND weight <= 1', name='ck_track_genres_weight'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_batch_id'], ['ingestion_batches.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'genre_id', name='uq_track_genres_pair')
    )
    op.create_table('track_languages',
    sa.Column('track_id', sa.String(length=36), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'language_code')
    )
    op.create_table('track_markets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('track_id', sa.String(length=36), nullable=False),
    sa.Column('market_id', sa.String(length=36), nullable=False),
    sa.Column('data_confidence', sa.Float(), nullable=False),
    sa.Column('source_batch_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('data_confidence >= 0 AND data_confidence <= 1', name='ck_track_markets_confidence'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_batch_id'], ['ingestion_batches.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'market_id', name='uq_track_markets_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_markets')
    op.drop_table('track_languages')
    op.drop_table('track_genres')
    op.drop_table('track_artists')
    op.drop_table('external_identifiers')
    op.drop_index('ix_tracks_title', table_name='tracks')
    op.drop_table('tracks')
    op.drop_table('artist_genres')
    op.drop_index('ix_releases_title', table_name='releases')
    op.drop_table('releases')
    op.drop_index('ix_artists_name', table_name='artists')
    op.drop_table('artists')
    op.drop_table('markets')
    op.drop_table('ingestion_batches')
    op.drop_table('genres')
    # ### end Alembic commands ###
